[mypy]
python_version = 3.12
ignore_missing_imports = True
no_strict_optional = True
exclude = ^test_.*\.py$
disable_error_code = override, attr-defined, arg-type, valid-type, no-redef

[mypy-venv.*]
ignore_errors = True
